name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options: 
        - dev
        - prod
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: |
            export TF_VAR_region="${{ github.event.inputs.environment }}"
            echo $TF_VAR_region
    - uses: hashicorp/setup-terraform@v2
    
    - run: terraform init
      working-directory: ./tf
    
    - id: plan
      run: terraform plan -no-color
      working-directory: ./tf
      
    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
