name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      environment_type:
        type: choice
        options: 
        - dev
        - prod
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Send greeting
      run: |
            export TF_VAR_environment_type="${{ github.event.inputs.environment }}"
            echo $TF_VAR_environment_type
    - uses: hashicorp/setup-terraform@v2
    
    - run: terraform init
      working-directory: tf
    
    - id: plan
      run: terraform plan -no-color
      working-directory: tf
